[tool.poetry]
name = "rfantibody"
version = "1.0.0"
description = ""
authors = [
  "Nate Bennett <nrbennett2@gmail.com>",
  "Joe Watchwell <joe.watchwell@gmail.com>"
]
readme = "README.md"
packages = [
{include = "rfantibody", from = "src"},
{include = "include"},
{include = "se3_transformer", from = "include/SE3Transformer"}
]

[[tool.poetry.source]]
name = "pypi"
priority = "primary"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.10,<3.11.dev0"
torch = { version="2.10.0", source="pytorch" }
torchaudio = { version="2.10.0", source="pytorch" }
torchvision = { version="0.25.0", source="pytorch" }
torch-utils = "*"
numpy = "1.*"
cuda-python = "12.8.*"
hydra-core = "*"
icecream = "*"
opt-einsum = "*"
e3nn = "*"
pyrsistent = "*"
biotite = "1.1.*"
urllib3 = ">=2.7.0"
idna = ">=3.15"
filelock = ">=3.20.3"
requests = ">=2.33.0"
jinja2 = ">=3.1.6"
pygments = ">=2.20.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = ">=9.0.3"
pandas = "*"

[tool.ruff.lint]
ignore = ["F821", "E741", "F401", "F405", "F403", "F841", "E731"] 

