# Config for sampling symmetric assemblies.

defaults:
  - base

inference:
  model_runner: AbSampler

preprocess:
  msaprev_bugfix: True
  hotspot_dim: 23
  use_selfcond_emb: False

antibody:
  target_pdb: null
  framework_pdb: null
  T_scheme: single_T
  design_loops: ['H1:','H2:','H3:','L1:','L2:','L3:']
  correct_selfcond: False
  no_bugfix_t1d_mask: True
  terminate_bad_targeting: null
  hotspot_termination_threshold: 10
  hotspot_termination_failures_permitted: 20
