# Base inference Configuration.

inference:
  input_pdb: null
  num_designs: 10
  design_startnum: 0
  ckpt_override_path: null
  symmetry: null
  recenter: True
  radius: 10.0
  model_only_neighbors: False
  num_recycles: 1
  recycle_schedule: null
  softmax_T: 1e-5
  output_prefix: samples/design
  write_trajectory: True
  scaffold_guided: False
  model_runner: NRBStyleSelfCond
  cautious: True
  recycle_between: False
  align_motif: True
  autoregressive_confidence: True
  no_confidence: True
  use_jw_selfcond: False
  symmetric_self_cond: True
  final_step: 1
  feed_true_xt: False
  annotate_termini: True
  deterministic: False
  trb_save_ckpt_path: null
  run_rf2_at_t: null
  final_state: False
  quiver: null

contigmap:
  contigs: null
  inpaint_str: null
  inpaint_seq: null
  provide_seq: null
  length: null

model:
  n_extra_block: 4
  n_main_block: 32
  n_ref_block: 4
  d_msa: 256
  d_msa_full: 64
  d_pair: 128
  d_templ: 64
  n_head_msa: 8
  n_head_pair: 4
  n_head_templ: 4
  d_hidden: 32
  d_hidden_templ: 32
  p_drop: 0.15
  SE3_param_full:
    num_layers: 1
    num_channels: 32
    num_degrees: 2
    n_heads: 4
    div: 4
    l0_in_features: 8
    l0_out_features: 8
    l1_in_features: 3
    l1_out_features: 2
    num_edge_features: 32
  SE3_param_topk:
    num_layers: 1
    num_channels: 32
    num_degrees: 2
    n_heads: 4
    div: 4
    l0_in_features: 64
    l0_out_features: 64
    l1_in_features: 3
    l1_out_features: 2
    num_edge_features: 64
  d_time_emb: null
  d_time_emb_proj: null
  freeze_track_motif: False
  use_motif_timestep: False
  input_seq_onehot: False

diffuser:
  T: 50
  b_0: 1e-2
  b_T: 7e-2
  schedule_type: linear
  so3_type: igso3
  aa_decode_steps: 40
  chi_type: wrapped_normal
  crd_scale: 0.0667
  schedule_kwargs: {}
  partial_T: null    
  so3_schedule_type: linear
  min_b: 1.5
  max_b: 2.5
  min_sigma: 0.02
  max_sigma: 1.5

seq_diffuser:
  s_b0: null
  s_bT: null
  schedule_type: null
  loss_type: null
  seqdiff: null

denoiser:
  noise_scale_ca: 1
  final_noise_scale_ca: 1
  ca_noise_schedule_type: constant
  noise_scale_frame: 1
  final_noise_scale_frame: 1
  frame_noise_schedule_type: constant
  noise_scale_torsion: 1
  rotation_scaling: null

ppi:
  hotspot_res: null

potentials:
  guiding_potentials: null 
  guide_scale: 10
  guide_decay: constant
  olig_inter_all : null
  olig_intra_all : null
  olig_custom_contact : null
  substrate: null

contig_settings:
  ref_idx: null
  hal_idx: null
  idx_rf: null
  inpaint_seq_tensor: null
  inpaint_str_tensor: null

preprocess:
  sidechain_input: False
  motif_sidechain_input: True
  sequence_decode: True
  d_t1d: 22
  d_t2d: 44
  prob_self_cond: 0.0
  str_self_cond: False
  seq_self_cond: False
  predict_previous: False
  selfcondition_msaprev: False
  selfcondition_pairprev: False
  selfcondition_stateprev: False
  
logging:
  inputs: False

scaffoldguided:
  scaffoldguided: False
  target_pdb: False
  target_path: null
  scaffold_list: null
  scaffold_dir: /databases/diffusion/scaffolds/scaffolds_b1_b2/
  sampled_insertion: 0
  sampled_N: 0
  sampled_C: 0
  ss_mask: 0
  systematic: False
  contig_crop: null
  radial_crop: null
  target_ss: null
  target_adj: null
  mask_loops: True
