# Base liklihood analysis config
defaults:
  - base

inference:
  autoregressive_confidence: True
  no_confidence: False
  output_prefix: 'test_output/runnb'
  softmax_T: 0.1
  ckpt_path: '/home/ahern/projects/BFF/rf_diffusion/models/no_fape/models/BFF_18.pt'
  input_pdb :  '/home/ahern/projects/BFF/rf_diffusion/training_pdbs/training_pdbs/test_epoch_0_1097_diff_cn_t_114true.pdb'
  num_designs: 1
  design_startnum: 0

diffuser:
  T: 200
  aa_decode_steps: 40
  min_sigma: 0.02
  max_sigma: 1.5
  min_b: 1.5
  max_b: 2.5
  so3_schedule_type: 'linear'
  b_0: 0.01
  b_T: 0.07
  crd_scale: 1
  schedule_type: 'linear'

preprocess:
  d_t1d: 22
  d_t2d: 44

denoiser:
  noise_scale_frame: 1

contigmap:
  contigs: ['58']

likelihood:
  T: null
  output_dir: ''
